# ============================================================
# HELPER: MOCK LOGGING & COM CLEANUP (Ensures no ghost processes)
# ============================================================
function Write-ToolLine ($Tool, $Action, $Details) { Write-Host "[$Tool] ${Action}: $Details" -ForegroundColor Cyan }
function Write-StatusLine ($Status, $Message) { Write-Host "[$Status] $Message" -ForegroundColor Green }

function Dispose-ComObject {
    param([Parameter(Mandatory = $true)]$ComObject)
    if ($null -ne $ComObject -and [System.Runtime.InteropServices.Marshal]::IsComObject($ComObject)) {
        [void][System.Runtime.InteropServices.Marshal]::ReleaseComObject($ComObject)
    }
}


# ============================================================
# BASIC OPERATIONS (Restored for System Compatibility)
# ============================================================

function Invoke-ExcelReadFile {
    <#
    .SYNOPSIS
    Reads data from an Excel file and returns it as a formatted string.

    .DESCRIPTION
    Opens an Excel workbook in read-only mode and extracts the used range as tab-separated values. Useful for quickly reading data into memory or passing to an LLM.

    .PARAMETER FilePath
    The absolute path to the Excel file.

    .PARAMETER SheetName
    Optional. The name of the sheet to read. Defaults to the active sheet.

    .PARAMETER MaxRows
    Optional. The maximum number of rows to read. Default is 100 to prevent memory exhaustion on massive sheets.

    .EXAMPLE
    Invoke-ExcelReadFile -FilePath "C:\Data.xlsx" -MaxRows 50
    Reads the first 50 rows of the active sheet.
    #>
    param(
        [Parameter(Mandatory = $true)][string]$FilePath,
        [string]$SheetName = "",
        [int]$MaxRows = 100
    )
    Write-ToolLine "Excel" "Reading File" $FilePath
    $excel = $null; $wb = $null; $ws = $null
    try {
        if (-not (Test-Path $FilePath)) { throw "File not found: $FilePath" }
        $excel = New-Object -ComObject Excel.Application
        $excel.Visible = $false
        $wb = $excel.Workbooks.Open($FilePath, $null, $true) # Read-only
        $ws = if ([string]::IsNullOrWhiteSpace($SheetName)) { $wb.ActiveSheet } else { $wb.Sheets.Item($SheetName) }
        
        $used = $ws.UsedRange
        $rowCount = [Math]::Min($used.Rows.Count, $MaxRows)
        $colCount = $used.Columns.Count
        
        $output = New-Object System.Text.StringBuilder
        for ($r = 1; $r -le $rowCount; $r++) {
            $line = @()
            for ($c = 1; $c -le $colCount; $c++) {
                $val = $ws.Cells.Item($r, $c).Text
                if ($val -match '[\t\n\r]') { $val = "'$($val -replace "[\t\n\r]", " ")'" }
                $line += $val
            }
            [void]$output.AppendLine(($line -join "`t"))
        }
        
        Write-StatusLine "OK" "Read $rowCount rows"
        return $output.ToString()
    }
    catch {
        return "ERROR: $_"
    }
    finally {
        if ($ws) { Dispose-ComObject $ws }
        if ($wb) { $wb.Close($false); Dispose-ComObject $wb }
        if ($excel) { $excel.Quit(); Dispose-ComObject $excel }
        [System.GC]::Collect(); [System.GC]::WaitForPendingFinalizers()
    }
}

function Invoke-ExcelCreateFile {
    <#
    .SYNOPSIS
    Creates a new Excel file from a TSV/CSV data string.

    .DESCRIPTION
    Takes raw tab-separated or comma-separated string data (often generated by an LLM) and writes it into a brand new Excel workbook, saving it to the specified path.

    .PARAMETER FilePath
    The absolute path where the new Excel file should be saved.

    .PARAMETER Data
    The raw text data containing rows separated by newlines, and columns separated by tabs or commas.

    .PARAMETER SheetName
    Optional. The name to give the worksheet. Defaults to 'Sheet1'.

    .EXAMPLE
    Invoke-ExcelCreateFile -FilePath "C:\Output.xlsx" -Data "Name`tAge`nAlice`t30"
    Creates an Excel file with two columns and two rows.
    #>
    param(
        [Parameter(Mandatory = $true)][string]$FilePath,
        [Parameter(Mandatory = $true)][string]$Data,
        [string]$SheetName = "Sheet1"
    )
    Write-ToolLine "Excel" "Creating File" $FilePath
    $excel = $null; $wb = $null; $ws = $null
    try {
        $excel = New-Object -ComObject Excel.Application
        $excel.Visible = $false
        $excel.DisplayAlerts = $false
        $wb = $excel.Workbooks.Add()
        $ws = $wb.ActiveSheet
        $ws.Name = $SheetName
        
        $rows = $Data -split "\r?\n"
        for ($r = 1; $r -le $rows.Count; $r++) {
            if ([string]::IsNullOrWhiteSpace($rows[$r-1])) { continue }
            $cols = $rows[$r-1] -split "\t"
            if ($cols.Count -eq 1 -and $cols[0] -match ",") { $cols = $rows[$r-1] -split "," }
            
            for ($c = 1; $c -le $cols.Count; $c++) {
                $ws.Cells.Item($r, $c).Value2 = $cols[$c-1]
            }
        }
        
        # Ensure directory exists
        $dir = [System.IO.Path]::GetDirectoryName($FilePath)
        if ($dir -and -not (Test-Path $dir)) { New-Item -Path $dir -ItemType Directory | Out-Null }
        
        $wb.SaveAs($FilePath)
        Write-StatusLine "OK" "Created $FilePath"
        return "Successfully created Excel file at $FilePath"
    }
    catch {
        return "ERROR: $_"
    }
    finally {
        if ($ws) { Dispose-ComObject $ws }
        if ($wb) { $wb.Close(); Dispose-ComObject $wb }
        if ($excel) { $excel.Quit(); Dispose-ComObject $excel }
        [System.GC]::Collect(); [System.GC]::WaitForPendingFinalizers()
    }
}

function Invoke-ExcelWriteCell {
    <#
    .SYNOPSIS
    Writes a value to a specific cell in an Excel file.

    .DESCRIPTION
    Opens an existing Excel workbook, targets a specific cell reference (like 'B2'), updates its value, and saves the file.

    .PARAMETER FilePath
    The absolute path to the Excel file.

    .PARAMETER Cell
    The cell reference to update (e.g., 'A1', 'C4').

    .PARAMETER Value
    The data value or formula to write into the cell.

    .PARAMETER SheetName
    Optional. The specific sheet to target. Defaults to the active sheet.

    .EXAMPLE
    Invoke-ExcelWriteCell -FilePath "C:\Data.xlsx" -Cell "B2" -Value "Approved"
    Writes the string 'Approved' into cell B2.
    #>
    param(
        [Parameter(Mandatory = $true)][string]$FilePath,
        [Parameter(Mandatory = $true)][string]$Cell,
        [Parameter(Mandatory = $true)][string]$Value,
        [string]$SheetName = ""
    )
    Write-ToolLine "Excel" "Writing Cell" "$Cell = $Value in $FilePath"
    $excel = $null; $wb = $null; $ws = $null
    try {
        if (-not (Test-Path $FilePath)) { throw "File not found: $FilePath" }
        $excel = New-Object -ComObject Excel.Application
        $excel.Visible = $false
        $wb = $excel.Workbooks.Open($FilePath)
        $ws = if ([string]::IsNullOrWhiteSpace($SheetName)) { $wb.ActiveSheet } else { $wb.Sheets.Item($SheetName) }
        
        $ws.Range($Cell).Value2 = $Value
        $wb.Save()
        
        Write-StatusLine "OK" "Cell updated"
        return "Successfully wrote '$Value' to cell $Cell in $FilePath"
    }
    catch {
        return "ERROR: $_"
    }
    finally {
        if ($ws) { Dispose-ComObject $ws }
        if ($wb) { $wb.Close(); Dispose-ComObject $wb }
        if ($excel) { $excel.Quit(); Dispose-ComObject $excel }
        [System.GC]::Collect(); [System.GC]::WaitForPendingFinalizers()
    }
}

# ============================================================
# CAPABILITY: METADATA & EXPLORATION
# ============================================================

function Invoke-ExcelGetMetadata {
    <#
    .SYNOPSIS
    Allows the LLM to instantly "see" the structure of the Excel file.

    .DESCRIPTION
    Quickly scans a workbook and returns a lightweight summary of all sheets, including their row counts, column counts, and column headers. This is much faster and safer than reading the entire file.

    .PARAMETER FilePath
    The absolute path to the Excel file.

    .EXAMPLE
    Invoke-ExcelGetMetadata -FilePath "C:\Report.xlsx"
    Returns a text summary of the sheets and their columns.
    #>
    param([Parameter(Mandatory = $true)][string]$FilePath)
    Write-ToolLine "Excel" "Getting Metadata" $FilePath
    
    $excel = $null; $wb = $null
    try {
        if (-not (Test-Path $FilePath)) { throw "File not found." }
        
        $excel = New-Object -ComObject Excel.Application
        $excel.Visible = $false
        $excel.DisplayAlerts = $false
        $wb = $excel.Workbooks.Open($FilePath, $null, $true) # Read-only
        
        $output = "Workbook: $($wb.Name)`n"
        foreach ($ws in $wb.Sheets) {
            $used = $ws.UsedRange
            $rows = $used.Rows.Count
            $cols = $used.Columns.Count
            
            $headers = @()
            if ($rows -gt 0 -and $cols -gt 0 -and $ws.Cells.Item(1, 1).Text -ne "") {
                # Read row 1 into an array much faster than cell-by-cell if possible, 
                # but cell-by-cell is safer for COM boundaries on row 1
                for ($c = 1; $c -le $cols; $c++) {
                    $val = $ws.Cells.Item(1, $c).Text
                    if (-not [string]::IsNullOrWhiteSpace($val)) { $headers += $val }
                }
            }
            $output += "- Sheet: '$($ws.Name)' | Rows: $rows | Cols: $cols`n"
            $output += "  Headers: $($headers -join ', ')`n"
            Dispose-ComObject $ws
        }
        
        Write-StatusLine "OK" "Metadata retrieved"
        return $output
    }
    catch {
        return "ERROR: $_"
    }
    finally {
        if ($wb) { $wb.Close($false); Dispose-ComObject $wb }
        if ($excel) { $excel.Quit(); Dispose-ComObject $excel }
        [System.GC]::Collect(); [System.GC]::WaitForPendingFinalizers()
    }
}

# ============================================================
# CAPABILITY: SQL QUERYING (ULTRA FAST)
# ============================================================

function Invoke-ExcelRunSQL {
    <#
    .SYNOPSIS
    Runs actual SQL queries directly against the Excel file.

    .DESCRIPTION
    Uses the Microsoft ACE OLEDB engine to execute standard SQL commands (like SELECT, WHERE, GROUP BY) against the data in an Excel sheet. This is extremely fast for querying large datasets without opening the file in the Excel UI.

    .PARAMETER FilePath
    The absolute path to the Excel file.

    .PARAMETER SqlQuery
    The SQL query to execute. Sheet names must be enclosed in brackets with a trailing dollar sign, e.g., [Sheet1$].

    .EXAMPLE
    Invoke-ExcelRunSQL -FilePath "C:\Data.xlsx" -SqlQuery "SELECT * FROM [Sheet1$] WHERE Status = 'Open'"
    Returns all rows where the Status column is 'Open'.
    #>
    param(
        [Parameter(Mandatory = $true)][string]$FilePath, 
        [Parameter(Mandatory = $true)][string]$SqlQuery
    )
    Write-ToolLine "Excel" "Running SQL Query" "$SqlQuery on $FilePath"
    
    try {
        if (-not (Test-Path $FilePath)) { throw "File not found." }
        
        $ext = [System.IO.Path]::GetExtension($FilePath).ToLower()
        $props = switch ($ext) {
            ".xls" { "Excel 8.0;HDR=YES;IMEX=1" }
            ".xlsb" { "Excel 12.0;HDR=YES;IMEX=1" }
            ".xlsm" { "Excel 12.0 Macro;HDR=YES;IMEX=1" }
            default { "Excel 12.0 Xml;HDR=YES;IMEX=1" } # .xlsx
        }
        
        $connString = "Provider=Microsoft.ACE.OLEDB.12.0;Data Source=$FilePath;Extended Properties=`"$props`";"
        
        $conn = New-Object System.Data.OleDb.OleDbConnection($connString)
        $conn.Open()
        
        $cmd = New-Object System.Data.OleDb.OleDbCommand($SqlQuery, $conn)
        $adapter = New-Object System.Data.OleDb.OleDbDataAdapter($cmd)
        $dataset = New-Object System.Data.DataSet
        [void]$adapter.Fill($dataset)
        $conn.Close()
        
        $table = $dataset.Tables[0]
        if ($table.Rows.Count -eq 0) { return "Query successful, but returned 0 rows." }

        # Output to CSV format for LLM reading
        $csvOutput = New-Object System.Text.StringBuilder
        $headers = $table.Columns | ForEach-Object { $_.ColumnName }
        [void]$csvOutput.AppendLine(($headers -join ","))
        
        foreach ($row in $table.Rows) {
            $rowItems = $row.ItemArray | ForEach-Object { 
                $val = $_.ToString()
                if ($val -match '[,"]') { "`"$($val -replace '"','""')`"" } else { $val }
            }
            [void]$csvOutput.AppendLine(($rowItems -join ","))
        }
        
        Write-StatusLine "OK" "SQL returned $($table.Rows.Count) rows"
        return $csvOutput.ToString()
    }
    catch {
        if ($_.Exception.Message -match "Microsoft.ACE.OLEDB") {
            return "ERROR: Microsoft Access Database Engine is not installed. Cannot run SQL on Excel. Install the ACE OLEDB 12.0/16.0 provider."
        }
        return "ERROR running SQL. Ensure Query uses Excel syntax (e.g., SELECT * FROM [Sheet1$]). Details: $_"
    }
}

# ============================================================
# CAPABILITY: DATA CLEANING (DEDUPLICATION)
# ============================================================

function Invoke-ExcelRemoveDuplicates {
    <#
    .SYNOPSIS
    Instantly removes duplicate rows based on specific columns.

    .DESCRIPTION
    Uses Excel's native RemoveDuplicates COM method to clean a dataset. You can specify exactly which columns should be checked for duplicate values.

    .PARAMETER FilePath
    The absolute path to the Excel file.

    .PARAMETER SheetName
    Optional. The sheet to clean. Defaults to 'Sheet1'.

    .PARAMETER ColumnsToCheck
    Optional. An array of column indices (1-based) to evaluate. If omitted, checks all columns.

    .EXAMPLE
    Invoke-ExcelRemoveDuplicates -FilePath "C:\Data.xlsx" -ColumnsToCheck @(1, 2)
    Removes rows where the combination of columns A and B are duplicates.
    #>
    param(
        [Parameter(Mandatory = $true)][string]$FilePath, 
        [string]$SheetName = "Sheet1", 
        [int[]]$ColumnsToCheck
    )
    Write-ToolLine "Excel" "Removing Duplicates" $FilePath
    
    $excel = $null; $wb = $null; $ws = $null
    try {
        $excel = New-Object -ComObject Excel.Application
        $excel.Visible = $false
        $excel.DisplayAlerts = $false
        
        $wb = $excel.Workbooks.Open($FilePath)
        $ws = try { $wb.Sheets.Item($SheetName) } catch { $wb.ActiveSheet }
        
        $used = $ws.UsedRange
        $startRows = $used.Rows.Count
        
        if ($null -eq $ColumnsToCheck -or $ColumnsToCheck.Count -eq 0) {
            $ColumnsToCheck = 1..$used.Columns.Count
        }
        
        # COM Interop requires a very specific [Object[]] cast for arrays in RemoveDuplicates
        [Object[]]$SafeArray = $ColumnsToCheck 
        
        # 1 = xlYes (Has Headers)
        $used.RemoveDuplicates([ref]$SafeArray, 1)
        
        $endRows = $ws.UsedRange.Rows.Count
        $removed = $startRows - $endRows
        
        $wb.Save()
        Write-StatusLine "OK" "Removed $removed duplicates"
        return "Successfully removed $removed duplicate rows from $SheetName."
    }
    catch {
        return "ERROR: $_"
    }
    finally {
        if ($ws) { Dispose-ComObject $ws }
        if ($wb) { $wb.Close($false); Dispose-ComObject $wb }
        if ($excel) { $excel.Quit(); Dispose-ComObject $excel }
        [System.GC]::Collect(); [System.GC]::WaitForPendingFinalizers()
    }
}

# ============================================================
# CAPABILITY: VISUAL DATA SCIENCE (HEATMAPS)
# ============================================================

function Invoke-ExcelApplyColorScale {
    <#
    .SYNOPSIS
    Applies an Excel Color Scale (Heatmap) or Data Bars.

    .DESCRIPTION
    Adds visual conditional formatting to a specified column, helping to instantly identify high/low values through a red-yellow-green heatmap or blue data bars.

    .PARAMETER FilePath
    The absolute path to the Excel file.

    .PARAMETER SheetName
    Optional. The sheet to modify. Defaults to 'Sheet1'.

    .PARAMETER ColumnLetter
    The letter of the column to format (e.g., 'C').

    .PARAMETER Type
    The type of formatting. Valid options: 'Heatmap', 'DataBar'. Default is 'Heatmap'.

    .EXAMPLE
    Invoke-ExcelApplyColorScale -FilePath "C:\Data.xlsx" -ColumnLetter "D" -Type "Heatmap"
    Applies a color scale to column D.
    #>
    param(
        [Parameter(Mandatory = $true)][string]$FilePath, 
        [string]$SheetName = "Sheet1", 
        [Parameter(Mandatory = $true)][string]$ColumnLetter,
        [ValidateSet("Heatmap", "DataBar")][string]$Type = "Heatmap"
    )
    Write-ToolLine "Excel" "Applying $Type" "Col $ColumnLetter in $FilePath"
    
    $excel = $null; $wb = $null; $ws = $null
    try {
        $excel = New-Object -ComObject Excel.Application
        $excel.Visible = $false
        $wb = $excel.Workbooks.Open($FilePath)
        $ws = try { $wb.Sheets.Item($SheetName) } catch { $wb.ActiveSheet }
        
        $lastRow = $ws.UsedRange.Rows.Count
        $range = $ws.Range("${ColumnLetter}2:${ColumnLetter}${lastRow}")
        $range.FormatConditions.Delete()
        
        if ($Type -eq "Heatmap") {
            $cs = $range.FormatConditions.AddColorScale(3)
            $cs.ColorScaleCriteria.Item(1).FormatColor.Color = 7039480   # Light Red
            $cs.ColorScaleCriteria.Item(2).FormatColor.Color = 8711167   # Yellow
            $cs.ColorScaleCriteria.Item(3).FormatColor.Color = 8125023   # Light Green
        }
        else {
            $db = $range.FormatConditions.AddDatabar()
            $db.BarColor.Color = 13012579 # Nice Blue
        }
        
        $wb.Save()
        Write-StatusLine "OK" "$Type applied to $ColumnLetter"
        return "Successfully applied $Type to column $ColumnLetter in $SheetName."
    }
    catch {
        return "ERROR: $_"
    }
    finally {
        if ($ws) { Dispose-ComObject $ws }
        if ($wb) { $wb.Close($false); Dispose-ComObject $wb }
        if ($excel) { $excel.Quit(); Dispose-ComObject $excel }
        [System.GC]::Collect(); [System.GC]::WaitForPendingFinalizers()
    }
}

# ============================================================
# NEW CAPABILITY: BEAUTIFY (EXECUTIVE FORMATTING)
# ============================================================

function Invoke-ExcelBeautify {
    <#
    .SYNOPSIS
    Transforms a raw data dump into a beautifully formatted, executive-ready table.

    .DESCRIPTION
    Applies professional styling to a sheet: bold headers with gray backgrounds, auto-filters, auto-fitted column widths, and frozen top panes.

    .PARAMETER FilePath
    The absolute path to the Excel file.

    .PARAMETER SheetName
    Optional. The sheet to beautify. Defaults to 'Sheet1'.

    .EXAMPLE
    Invoke-ExcelBeautify -FilePath "C:\Report.xlsx"
    Formats the active data region on Sheet1.
    #>
    param([Parameter(Mandatory = $true)][string]$FilePath, [string]$SheetName = "Sheet1")
    Write-ToolLine "Excel" "Beautifying Sheet" $FilePath
    
    $excel = $null; $wb = $null; $ws = $null
    try {
        $excel = New-Object -ComObject Excel.Application
        $excel.Visible = $false
        $wb = $excel.Workbooks.Open($FilePath)
        $ws = try { $wb.Sheets.Item($SheetName) } catch { $wb.ActiveSheet }
        
        $usedRange = $ws.UsedRange
        
        # 1. Bold Headers & Background Color
        $headerRange = $ws.Range($ws.Cells.Item(1, 1), $ws.Cells.Item(1, $usedRange.Columns.Count))
        $headerRange.Font.Bold = $true
        $headerRange.Interior.Color = 14277081 # Light Grey
        
        # 2. Add AutoFilter
        $headerRange.AutoFilter(1) | Out-Null
        
        # 3. AutoFit Columns
        $usedRange.Columns.AutoFit() | Out-Null
        
        # 4. Freeze Top Row
        $excel.ActiveWindow.SplitRow = 1
        $excel.ActiveWindow.FreezePanes = $true
        
        $wb.Save()
        Write-StatusLine "OK" "Data beautified"
        return "Successfully formatted and beautified $SheetName."
    }
    catch {
        return "ERROR: $_"
    }
    finally {
        if ($ws) { Dispose-ComObject $ws }
        if ($wb) { $wb.Close($false); Dispose-ComObject $wb }
        if ($excel) { $excel.Quit(); Dispose-ComObject $excel }
        [System.GC]::Collect(); [System.GC]::WaitForPendingFinalizers()
    }
}

# ============================================================
# NEW CAPABILITY: CHART GENERATION
# ============================================================

function Invoke-ExcelAddChart {
    <#
    .SYNOPSIS
    Generates visually appealing embedded charts natively in Excel.

    .DESCRIPTION
    Creates a new embedded chart (Bar, Line, or Pie) based on a specified data range and places it next to the data in the worksheet.

    .PARAMETER FilePath
    The absolute path to the Excel file.

    .PARAMETER DataRange
    The range of cells to chart (e.g., 'A1:B10'). Ensure it includes headers.

    .PARAMETER SheetName
    Optional. The sheet containing the data. Defaults to 'Sheet1'.

    .PARAMETER ChartType
    Optional. The type of chart to generate: 'Bar', 'Line', 'Pie'. Default is 'Bar'.

    .PARAMETER ChartTitle
    Optional. The title to display above the chart.

    .EXAMPLE
    Invoke-ExcelAddChart -FilePath "C:\Data.xlsx" -DataRange "A1:B5" -ChartType "Pie" -ChartTitle "Sales Dist"
    Creates a Pie chart for the data in A1:B5.
    #>
    param(
        [Parameter(Mandatory = $true)][string]$FilePath,
        [Parameter(Mandatory = $true)][string]$DataRange, # e.g., "A1:B10"
        [string]$SheetName = "Sheet1",
        [ValidateSet("Bar", "Line", "Pie")][string]$ChartType = "Bar",
        [string]$ChartTitle = "Data Chart"
    )
    Write-ToolLine "Excel" "Creating $ChartType Chart" $FilePath
    
    $excel = $null; $wb = $null; $ws = $null
    try {
        $excel = New-Object -ComObject Excel.Application
        $excel.Visible = $false
        $wb = $excel.Workbooks.Open($FilePath)
        $ws = try { $wb.Sheets.Item($SheetName) } catch { $wb.ActiveSheet }
        
        $range = $ws.Range($DataRange)
        
        # AddChart2(Style, XlChartType, Left, Top, Width, Height)
        $xlChartType = switch ($ChartType) {
            "Bar" { 51 } # xlColumnClustered
            "Line" { 4 }  # xlLine
            "Pie" { 5 }  # xlPie
        }
        
        # Position chart 2 columns to the right of the data
        $leftPos = $range.Left + $range.Width + 20
        $topPos = $range.Top
        
        $chartObj = $ws.Shapes.AddChart2(251, $xlChartType, $leftPos, $topPos, 350, 250)
        $chart = $chartObj.Chart
        $chart.SetSourceData($range)
        $chart.HasTitle = $true
        $chart.ChartTitle.Text = $ChartTitle
        
        $wb.Save()
        Write-StatusLine "OK" "Chart generated"
        return "Successfully created $ChartType chart titled '$ChartTitle' using range $DataRange."
    }
    catch {
        return "ERROR: $_"
    }
    finally {
        if ($ws) { Dispose-ComObject $ws }
        if ($wb) { $wb.Close($false); Dispose-ComObject $wb }
        if ($excel) { $excel.Quit(); Dispose-ComObject $excel }
        [System.GC]::Collect(); [System.GC]::WaitForPendingFinalizers()
    }
}

# ============================================================
# NEW CAPABILITY: CSV TO NATIVE EXCEL PIPELINE
# ============================================================

function Convert-CsvToExcel {
    <#
    .SYNOPSIS
    Extremely fast ingestion of raw CSV data into a native .xlsx file.

    .DESCRIPTION
    Uses the Excel COM engine to securely and efficiently convert a standard CSV file into a fully featured Excel Workbook (.xlsx) format.

    .PARAMETER CsvPath
    The absolute path to the source CSV file.

    .PARAMETER ExcelPath
    The absolute path where the new .xlsx file should be saved.

    .EXAMPLE
    Convert-CsvToExcel -CsvPath "C:\raw.csv" -ExcelPath "C:\processed.xlsx"
    Converts raw.csv to processed.xlsx.
    #>
    param(
        [Parameter(Mandatory = $true)][string]$CsvPath,
        [Parameter(Mandatory = $true)][string]$ExcelPath
    )
    Write-ToolLine "Excel" "Converting CSV to XLSX" $ExcelPath
    
    $excel = $null; $wb = $null; $ws = $null
    try {
        if (-not (Test-Path $CsvPath)) { throw "CSV File not found." }
        
        $excel = New-Object -ComObject Excel.Application
        $excel.Visible = $false
        $excel.DisplayAlerts = $false
        
        # Open CSV directly in Excel engine
        $wb = $excel.Workbooks.Open($CsvPath)
        
        # 51 = xlOpenXMLWorkbook (.xlsx)
        $wb.SaveAs($ExcelPath, 51)
        
        Write-StatusLine "OK" "Conversion complete"
        return "Successfully converted CSV to Excel at $ExcelPath. You can now use Invoke-ExcelBeautify on it."
    }
    catch {
        return "ERROR: $_"
    }
    finally {
        if ($wb) { $wb.Close($false); Dispose-ComObject $wb }
        if ($excel) { $excel.Quit(); Dispose-ComObject $excel }
        [System.GC]::Collect(); [System.GC]::WaitForPendingFinalizers()
    }
}

# ============================================================
# CAPABILITY: REPORT GENERATION
# ============================================================

function Invoke-ExcelExportPDF {
    <#
    .SYNOPSIS
    Converts an Excel analysis into a polished PDF report.

    .DESCRIPTION
    Exports either a specific worksheet or the entire workbook into a PDF file. Automatically configures page setup (landscape, fit to 1 page wide) for optimal viewing.

    .PARAMETER FilePath
    The absolute path to the source Excel file.

    .PARAMETER PdfPath
    The absolute path where the PDF report should be saved.

    .PARAMETER SheetName
    Optional. The specific sheet to export (if EntireWorkbook is not used). Defaults to 'Sheet1'.

    .PARAMETER EntireWorkbook
    Optional switch. If specified, exports all sheets in the workbook into a single PDF.

    .EXAMPLE
    Invoke-ExcelExportPDF -FilePath "C:\Report.xlsx" -PdfPath "C:\Report.pdf" -EntireWorkbook
    Exports the entire Excel file to a PDF.
    #>
    param(
        [Parameter(Mandatory = $true)][string]$FilePath, 
        [Parameter(Mandatory = $true)][string]$PdfPath, 
        [string]$SheetName = "Sheet1",
        [switch]$EntireWorkbook
    )
    Write-ToolLine "Excel" "Exporting PDF" $PdfPath
    
    $excel = $null; $wb = $null; $ws = $null
    try {
        if (-not (Test-Path $FilePath)) { throw "File not found." }
        $excel = New-Object -ComObject Excel.Application
        $excel.Visible = $false
        
        $wb = $excel.Workbooks.Open($FilePath)
        
        if ($EntireWorkbook) {
            foreach ($sheet in $wb.Sheets) {
                $sheet.PageSetup.Zoom = $false
                $sheet.PageSetup.FitToPagesWide = 1
                $sheet.PageSetup.Orientation = 2 # Landscape
            }
            # 0 = xlTypePDF
            $wb.ExportAsFixedFormat(0, $PdfPath)
        }
        else {
            $ws = try { $wb.Sheets.Item($SheetName) } catch { $wb.ActiveSheet }
            $ws.PageSetup.Zoom = $false
            $ws.PageSetup.FitToPagesWide = 1
            $ws.PageSetup.FitToPagesTall = $false
            $ws.PageSetup.Orientation = 2 # Landscape
            
            $ws.ExportAsFixedFormat(0, $PdfPath)
        }
        
        Write-StatusLine "OK" "Exported to $PdfPath"
        return "Successfully generated PDF report at $PdfPath"
    }
    catch {
        return "ERROR: $_"
    }
    finally {
        if ($ws) { Dispose-ComObject $ws }
        if ($wb) { $wb.Close($false); Dispose-ComObject $wb }
        if ($excel) { $excel.Quit(); Dispose-ComObject $excel }
        [System.GC]::Collect(); [System.GC]::WaitForPendingFinalizers()
    }
}